CREATE TABLE Person (
    person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL
);

insert into Person (full_name, year_of_birth) values ('Mallory Lesslie', 2010);
insert into Person (full_name, year_of_birth) values ('Casar Demeter', 1988);
insert into Person (full_name, year_of_birth) values ('Christos Autin', 2009);
insert into Person (full_name, year_of_birth) values ('Ricardo Harries', 2011);
insert into Person (full_name, year_of_birth) values ('Carlotta Yelding', 1978);
insert into Person (full_name, year_of_birth) values ('Reidar Deares', 1997);
insert into Person (full_name, year_of_birth) values ('Joscelin Maddrah', 1995);
insert into Person (full_name, year_of_birth) values ('Meghan Meakin', 1999);
insert into Person (full_name, year_of_birth) values ('Rustie Bairnsfather', 2009);
insert into Person (full_name, year_of_birth) values ('Brynna Tinsey', 1993);
insert into Person (full_name, year_of_birth) values ('Georgeanna Lenchenko', 2006);
insert into Person (full_name, year_of_birth) values ('Nicolis Orthmann', 2010);
insert into Person (full_name, year_of_birth) values ('Kakalina Toyne', 1997);
insert into Person (full_name, year_of_birth) values ('Barrie Hullins', 1993);
insert into Person (full_name, year_of_birth) values ('Aggie Mariel', 1996);
insert into Person (full_name, year_of_birth) values ('Allison Ickovitz', 1993);
insert into Person (full_name, year_of_birth) values ('Parrnell Pedican', 2002);
insert into Person (full_name, year_of_birth) values ('Coleman Stoeck', 1997);
insert into Person (full_name, year_of_birth) values ('Arman Griggs', 2008);
insert into Person (full_name, year_of_birth) values ('Madelin Gleadle', 2002);


CREATE TABLE Book (
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_name varchar(100) NOT NULL,
    book_author varchar(100) NOT NULL,
    year_of_book int NOT NULL,
    person_id int REFERENCES Person(person_id) ON DELETE SET NULL,
    taken_at timestamp
);

insert into Book (book_name, book_author, year_of_book) values ('Harry Potter','Joan Rowling' ,2000);
insert into Book (full_name, book_author, year_of_book) values ('The Lord Of The Rings','John R. Tolkien' ,1960);
